### ISSUE TITLE
FLAME lattice output from machine object

### ISSUE THREAD

**Issue by archman** [frib-high-level-controls/flame-utils#1]
The present feature of `phantasy.generate_latfile()` is to generate a concise lattice file from machine object or original lattice file, however, some information will not be retained, e.g. user input comments, elements that are not used in the lattice line definition, as well as the input format/style. This new feature should be able to provide an option to preserve these information, mainly for the understandability, if the lattice file is not only consumed by the virtual accelerator.

**Comment by kryv** [comment]
I have add support "new parameter definition"  and  "initial beam state input" to `generate_latfile`
(Commit: 50c5c46b6be348141188a0f008b783908e3a18e3)

Next, I will work for supporting "original file comment".
