### ISSUE TITLE
Request of renaming attribute names in state.py and output.py

### ISSUE THREAD

**Issue by yoshimotFRIB** [frib-high-level-controls/flame-utils#17]
Could you change some attribute names as follows ?

rule1: The attribute including the information of each charge state at some longitudinal position should have 'l' as the initial of 'list' at the end. 

rule2: The statistical value for multi-charge state beams do not have '_env'. 

class BeamState(object) in 'flame-utils/flame_utils/core/state.py'
def collect_data(result, **kws) in 'flame-utils/flame_utils/io/output.py'
#-----------------------------------
x0 => xcenl
y0 => ycenl
xp0 => xpcenl
yp0 => ypcenl
phi0 => phil
dEk0 => dEkl
x0_rms => xrmsl
y0_rms => xprmsl
xp0_rms => yrmsl
yp0_rms => yprmsl
phi0_rms => phirmsl
dEk0_rms => dEkrmsl
x0_env => xcen
y0_env => ycen
xp0_env => xpcen
yp0_env => ypcen
phi0_env => phicen
dEk0_env => dEkcen
moment0_env => moment0
moment0 => moment0l
moment0_rms => moment0rmsl
moment1 => moment1l
#-----------------------------------

**Comment by kryv** [comment]
moment0_env => moment0
moment0 => moment0l
moment0_rms => moment0rmsl
moment1 => moment1l

--------------------------

Can you modify these renamings ?
moment0 is duplicated. It means the same name has different return value between flame and flame-utils. I thinks it is not convenient.

For example,

moment0_env => cenvector
moment0 => cenvectorl
moment0_rms => envmatrix
moment1 => envmatrixl

**Comment by archman** [comment]
@yoshimotFRIB For example, for the name of `xcenl`, `xcent_all` may be better to understand.

**Comment by yoshimotFRIB** [comment]
**@kryv** I almost agree with you.
new rule 1 :  'moment0' is  replaced with 'cenvector'.
new rule 2 :  'moment1' is  replaced with 'beammatrix'.


**@archman** I completely agree with you.
new rule 3:  '_all' is the list including multi-charge state information.
 
My and Tomo's suggestions are as follows.
#-----------------------------------
x0 => xcen_all
y0 => ycen_all
xp0 => xpcen_all
yp0 => ypcen_all
phi0 => phi_all
dEk0 => dEk_all
x0_rms => xrms_all
y0_rms => xprms_all
xp0_rms => yrms_all
yp0_rms => yprms_all
phi0_rms => phirms_all
dEk0_rms => dEkrms_all
x0_env => xcen
y0_env => ycen
xp0_env => xpcen
yp0_env => ypcen
phi0_env => phicen
dEk0_env => dEkcen
moment0_env => cenvector
moment0 => cenvector_all
moment0_rms => cenvectorrms_all
moment1 => beammatrix_all
#-----------------------------------

**Comment by kryv** [comment]
For the new attributes, we can just use followings
`np.sqrt(S.moment1[0,0,:])` => xrms_all
`np.sqrt(S.moment1[1,1,:])` => xprms_all
`np.sqrt(S.moment1[2,2,:])` => yrms_all
`np.sqrt(S.moment1[3,3,:])` => yprms_all
`np.sqrt(S.moment1[4,4,:])` => phirms_all
`np.sqrt(S.moment1[5,5,:])` => dEkrms_all

**Comment by archman** [comment]
@yoshimotFRIB Could you please add the physics meaning for each attribute? So that I can update much more informatively.

**Comment by yoshimotFRIB** [comment]
**@archman** I completely agree with you.
I fixed  their attribute names and added physics meanings in my previous comment.

**Comment by archman** [comment]
>For the new attributes, we can just use followings
np.sqrt(S.moment1[0,0,:]) => xrms_all
np.sqrt(S.moment1[1,1,:]) => xprms_all
np.sqrt(S.moment1[2,2,:]) => yrms_all
np.sqrt(S.moment1[3,3,:]) => yprms_all
np.sqrt(S.moment1[4,4,:]) => phirms_all
np.sqrt(S.moment1[5,5,:]) => dEkrms_all

@kryv missed `sqrt`?

**Comment by kryv** [comment]
@archman yes. `sqrt` is required.
